name: ${LoginSecurity}
version: ${0.1}
main: com.lenis0012.bukkit.loginsecurity.LoginSecurity
author: lenis0012
description: The #1 Auth plugin
commands:
  login:
    description: Login with your account.
    usage: /l <password>
  register:
    description: Set a password for your account.
    usage: /r <password>
  changepassword:
    description: Change your account password.
    aliases: [changepass]
    usage: /changepass <old pass> <new pass>
  logout:
    description: Log out of your account.
    usage: /logout
  unregister:
    description: Unregister your account.
    usage: /unregister <current password>
  lac:
    description: LoginSecurity Admin command.
    usage: /lac
